// Dev-server endpoint: turn a product URL into a catalog entry + FurnitureSpec (Dianne's schema).
// Scrapes the page, asks OpenAI for structured data, caches by URL, and enforces a spend cap.
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const PRICING = { "gpt-4o-mini": [0.15, 0.6], "gpt-4.1-mini": [0.4, 1.6], "gpt-4.1-nano": [0.1, 0.4] }; // USD per 1M tokens (in, out)

export function createImporter({ root, apiKey, model = "gpt-4o-mini", budgetUsd = 5 }) {
  const cacheDir = join(root, ".cache", "imports");
  const usageFile = join(root, ".cache", "openai-usage.json");
  mkdirSync(cacheDir, { recursive: true });

  const readUsage = () => { try { return JSON.parse(readFileSync(usageFile, "utf8")); } catch { return { usd: 0, calls: 0 }; } };
  const addUsage = (usd) => { const u = readUsage(); u.usd += usd; u.calls += 1; writeFileSync(usageFile, JSON.stringify(u)); return u; };

  async function importProduct(url) {
    const key = createHash("sha1").update(url).digest("hex").slice(0, 16);
    const cachePath = join(cacheDir, `${key}.json`);
    if (existsSync(cachePath)) return { ...JSON.parse(readFileSync(cachePath, "utf8")), cached: true };

    const page = await scrape(url);
    if (!apiKey) throw new Error("OPENAI_API_KEY is not set in apps/web/.env");
    const usage = readUsage();
    if (usage.usd >= budgetUsd) throw new Error(`OpenAI budget cap reached ($${usage.usd.toFixed(2)} of $${budgetUsd}). Delete .cache/openai-usage.json to reset.`);

    const result = await askModel({ apiKey, model, page, url });
    const cost = estimateCost(model, result.usage);
    const total = addUsage(cost);
    console.log(`[import] ${url}\n  tokens in=${result.usage.prompt_tokens} out=${result.usage.completion_tokens} → $${cost.toFixed(4)} (session $${total.usd.toFixed(3)} of $${budgetUsd})`);

    const data = result.data;
    const id = `imp-${key}`;
    const spec = tidySpec({ ...data.spec, schemaVersion: "1.0" });
    const specPath = `/demo-assets/generated/${id}.spec.json`;
    mkdirSync(join(root, "public", "demo-assets", "generated"), { recursive: true });
    writeFileSync(join(root, "public", specPath), JSON.stringify(spec, null, 2));

    const category = ["bed", "desk", "chair", "shelf", "lamp", "decor"].includes(data.category) ? data.category : "misc";
    const product = {
      id, title: data.title, category, priceUsd: Math.max(0, Math.round(data.priceUsd)), merchant: page.host, sourceUrl: url,
      imageUrl: page.images[0] ?? "", dimensionsM: data.dimensionsM, styleTags: data.styleTags.slice(0, 6), colorTags: data.colorTags.slice(0, 6), modelAssetId: `asset-${id}`,
    };
    const asset = {
      id: `asset-${id}`, productId: id, glbUrl: `spec:${specPath}`, dimensionsM: data.dimensionsM, pivot: "bottom-center", forwardAxis: "+Z",
      generationMethod: "gpt-blender", status: "ready",
      disclosure: `FurnitureSpec generated by OpenAI ${model} from ${page.host} (${page.imagesUsed ?? 0} product image(s) + page text), interpreted by DreamGrid's constrained builder. Dimensions ${data.dimensionsSource}. Not a manufacturer model.`,
    };
    // Persist into the catalog so it survives reloads.
    const catalogPath = join(root, "public", "demo-assets", "catalog.json");
    const catalog = JSON.parse(readFileSync(catalogPath, "utf8"));
    catalog.products = catalog.products.filter((p) => p.id !== id).concat(product);
    catalog.assets = catalog.assets.filter((a) => a.id !== asset.id).concat(asset);
    writeFileSync(catalogPath, JSON.stringify(catalog, null, 2) + "\n");

    const out = { product, asset, spec, cost, page: { title: page.title, images: page.images, dimensionsText: page.dimensionsText } };
    writeFileSync(cachePath, JSON.stringify(out));
    return out;
  }

  return { importProduct, readUsage };
}

function estimateCost(model, usage) {
  const [pin, pout] = PRICING[model] ?? [1, 4];
  return ((usage?.prompt_tokens ?? 0) * pin + (usage?.completion_tokens ?? 0) * pout) / 1e6;
}

/** Fetch the page and pull out title, price, images, dimension mentions, and a text digest. */
export async function scrape(url) {
  const res = await fetch(url, {
    headers: { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36", Accept: "text/html,*/*" },
    redirect: "follow",
  });
  if (!res.ok) throw new Error(`Couldn't fetch the page (${res.status})`);
  const html = (await res.text()).slice(0, 2_000_000);
  const host = new URL(url).host.replace(/^www\./, "");
  const meta = (p) => { const m = html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${p}["'][^>]*content=["']([^"']+)["']`, "i")) || html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]*(?:property|name)=["']${p}["']`, "i")); return m ? decode(m[1]) : ""; };

  // JSON-LD Product blocks
  const ld = [];
  for (const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)) {
    try { const j = JSON.parse(m[1].trim()); (Array.isArray(j) ? j : [j]).forEach((x) => collectLd(x, ld)); } catch { /* ignore */ }
  }
  const product = ld.find((x) => /product/i.test(String(x["@type"])));
  const offers = product?.offers ? (Array.isArray(product.offers) ? product.offers[0] : product.offers) : null;
  const price = Number(offers?.price ?? offers?.lowPrice ?? meta("product:price:amount") ?? meta("og:price:amount")) || 0;

  const images = [];
  const push = (u) => { if (!u) return; try { const abs = new URL(u, url).toString(); if (/^https?:/.test(abs) && !images.includes(abs)) images.push(abs); } catch { /* ignore */ } };
  push(meta("og:image")); push(meta("twitter:image"));
  const pi = product?.image; (Array.isArray(pi) ? pi : [pi]).forEach((x) => push(typeof x === "string" ? x : x?.url));
  for (const m of html.matchAll(/<img[^>]+src=["']([^"']+)["'][^>]*>/gi)) { if (images.length >= 6) break; if (/product|gallery|hero|main|zoom/i.test(m[0]) && !/logo|icon|sprite|svg/i.test(m[1])) push(m[1]); }

  const text = decode(html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " "));
  const dimRe = /(?:(?:width|height|depth|length|diameter|w|h|d|l)\s*[:=]?\s*)?\d+(?:[.,]\d+)?\s*(?:"|''|in(?:ch(?:es)?)?|cm|mm)\b[^.;|]{0,40}/gi;
  const dimensionsText = [...new Set([...(text.match(dimRe) || [])].map((s) => s.trim()))].filter((s) => /width|height|depth|length|diam|\bw\b|\bh\b|\bd\b|x\s*\d/i.test(s) || /"|in\b|cm/.test(s)).slice(0, 25).join(" | ");
  const ldDims = product ? ["width", "height", "depth"].map((k) => product[k] ? `${k}: ${JSON.stringify(product[k])}` : "").filter(Boolean).join(", ") : "";

  return {
    host, title: decode(product?.name || meta("og:title") || (html.match(/<title[^>]*>([^<]*)<\/title>/i) || [])[1] || ""),
    description: decode(product?.description || meta("og:description") || meta("description") || ""),
    price, images: images.slice(0, 4), dimensionsText: [ldDims, dimensionsText].filter(Boolean).join(" | "), digest: text.slice(0, 3500),
  };
}

function collectLd(x, out) {
  if (!x || typeof x !== "object") return;
  if (x["@type"]) out.push(x);
  if (Array.isArray(x["@graph"])) x["@graph"].forEach((g) => collectLd(g, out));
}
function decode(s) { return String(s).replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&nbsp;/g, " ").trim(); }

const SPEC_SCHEMA = {
  type: "object", additionalProperties: false,
  required: ["title", "category", "priceUsd", "dimensionsM", "dimensionsSource", "styleTags", "colorTags", "spec"],
  properties: {
    title: { type: "string" },
    category: { type: "string", enum: ["bed", "desk", "chair", "shelf", "lamp", "decor", "misc"] },
    priceUsd: { type: "number" },
    dimensionsM: { type: "array", items: { type: "number" }, minItems: 3, maxItems: 3 },
    dimensionsSource: { type: "string", description: "Where the dimensions came from: 'from the listing' or 'estimated (typical size)'." },
    styleTags: { type: "array", items: { type: "string" } },
    colorTags: { type: "array", items: { type: "string" } },
    spec: {
      type: "object", additionalProperties: false,
      required: ["name", "category", "dimensionsM", "materials", "parts"],
      properties: {
        name: { type: "string" },
        category: { type: "string", enum: ["bed", "desk", "chair", "shelf", "lamp", "decor"] },
        dimensionsM: { type: "array", items: { type: "number" }, minItems: 3, maxItems: 3 },
        materials: { type: "array", items: { type: "object", additionalProperties: false, required: ["id", "name", "baseColorHex", "roughness", "metallic"], properties: { id: { type: "string" }, name: { type: "string" }, baseColorHex: { type: "string" }, roughness: { type: "number" }, metallic: { type: "number" } } } },
        parts: { type: "array", items: { type: "object", additionalProperties: false, required: ["id", "primitive", "role", "dimensionsM", "positionM", "rotationDeg", "materialId", "cornerRadiusM", "repeat"], properties: {
          id: { type: "string" }, primitive: { type: "string", enum: ["box", "rounded-box", "cylinder", "shade"] }, role: { type: "string", enum: ["body", "top", "leg", "shelf", "support", "accent"] },
          dimensionsM: { type: "array", items: { type: "number" }, minItems: 3, maxItems: 3 }, positionM: { type: "array", items: { type: "number" }, minItems: 3, maxItems: 3 }, rotationDeg: { type: "array", items: { type: "number" }, minItems: 3, maxItems: 3 },
          materialId: { type: "string" }, cornerRadiusM: { type: ["number", "null"] },
          repeat: { type: ["object", "null"], additionalProperties: false, required: ["count", "offsetM"], properties: { count: { type: "integer" }, offsetM: { type: "array", items: { type: "number" }, minItems: 3, maxItems: 3 } } },
        } } },
      },
    },
  },
};

const SYSTEM = `You turn an online furniture listing into (1) catalog data and (2) a FurnitureSpec: a small set of primitives that a trusted builder assembles into a 3D model.
Rules for the spec:
- Units are meters. Y is up. The model's origin is the CENTER of its floor footprint: parts sit between y=0 (floor) and y=height. X spans -width/2..width/2, Z spans -depth/2..depth/2. The FRONT of the item faces +Z.
- positionM is the CENTER of each part. dimensionsM is [width(x), height(y), depth(z)] of that part. For cylinders width and depth are the diameter, height the length along Y (use rotationDeg to lay one on its side). "shade" is an open lampshade (tapered).
- Use 4-30 parts. Keep everything inside the overall dimensions and make the parts touch/support each other like the real object:
  a tabletop or seat is a thin box whose TOP face is at the item's height (center y = height - thickness/2); legs are boxes or cylinders
  from y=0 up to the underside of what they hold (center y = legHeight/2), placed near the corners (x,z = ±(width/2 - inset)).
  Four legs = one part with repeat count 2 along X plus a second part repeated along X at the other Z, or four separate parts.
  Beds: frame box low, mattress box on top, headboard box at the back (z = -depth/2). Shelves: side panels + several thin shelf boxes.
  Colors from the photos; matte fabrics roughness ~0.9, wood ~0.6, metal ~0.3 with metallic 0.8.
- Overall dimensionsM = [width, height, depth] in meters, from the listing when present (convert inches/cm). Otherwise estimate a typical size and say so in dimensionsSource.
- Category from the enum; use "misc" only if nothing fits (spec.category must still be one of the six).
Return only JSON matching the schema.`;

/** Download an image and return it as a data URL if it's a format the model accepts (jpeg/png/webp/gif), else null. */
async function inlineImage(src) {
  try {
    const res = await fetch(src, { headers: { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/124 Safari/537.36", Accept: "image/jpeg,image/png,image/webp,image/gif,image/*;q=0.8" }, redirect: "follow" });
    if (!res.ok) return null;
    const type = (res.headers.get("content-type") || "").split(";")[0].trim().toLowerCase();
    if (!["image/jpeg", "image/png", "image/webp", "image/gif"].includes(type)) return null;
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length < 2000 || buf.length > 4_000_000) return null;
    return `data:${type};base64,${buf.toString("base64")}`;
  } catch { return null; }
}

async function askModel({ apiKey, model, page, url }) {
  const content = [{ type: "text", text: `URL: ${url}\nSite: ${page.host}\nTitle: ${page.title}\nDescription: ${page.description}\nPrice found on page: ${page.price || "unknown"}\nDimension mentions: ${page.dimensionsText || "none"}\nPage text digest:\n${page.digest}` }];
  const inlined = (await Promise.all(page.images.slice(0, 5).map(inlineImage))).filter(Boolean).slice(0, 3);
  page.imagesUsed = inlined.length;
  for (const data of inlined) content.push({ type: "image_url", image_url: { url: data, detail: "low" } });
  const body = {
    model, max_tokens: 2500, temperature: 0.2,
    messages: [{ role: "system", content: SYSTEM }, { role: "user", content }],
    response_format: { type: "json_schema", json_schema: { name: "furniture_import", strict: true, schema: SPEC_SCHEMA } },
  };
  const res = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` }, body: JSON.stringify(body) });
  const json = await res.json();
  if (!res.ok) throw new Error(`OpenAI: ${json.error?.message ?? res.status}`);
  const text = json.choices?.[0]?.message?.content ?? "{}";
  return { data: JSON.parse(text), usage: json.usage ?? {} };
}

/** Same fix as src/interactions/specBuilder.ts tidySpec, applied before the spec is saved. */
function tidySpec(spec) {
  const H = spec.dimensionsM[1];
  const parts = spec.parts.map((p) => ({ ...p, dimensionsM: [...p.dimensionsM], positionM: [...p.positionM] }));
  const tops = parts.filter((p) => p.role === "top");
  const legs = parts.filter((p) => p.role === "leg" || p.role === "support");
  if (tops.length && legs.length) {
    for (const t of tops) if (t.positionM[1] + t.dimensionsM[1] / 2 < H * 0.85) t.positionM[1] = H - t.dimensionsM[1] / 2;
    const underside = Math.min(...tops.map((t) => t.positionM[1] - t.dimensionsM[1] / 2));
    for (const l of legs) {
      const legTop = l.positionM[1] + l.dimensionsM[1] / 2;
      if (legTop > underside + 1e-3 && l.rotationDeg.every((r) => Math.abs(r) < 1)) {
        const bottom = Math.max(0, l.positionM[1] - l.dimensionsM[1] / 2);
        l.dimensionsM[1] = Math.max(0.01, underside - bottom);
        l.positionM[1] = bottom + l.dimensionsM[1] / 2;
      }
    }
  }
  return { ...spec, parts };
}
