import { describe, expect, it, vi } from "vitest";
import type { GenerationJob, PreparedImport, Product } from "@contracts";
import { createGenerationClient, waitForGeneration, furnitureImageDataUrl } from "./generationClient";
import { reviewedRequest, dimensionDisclosure, generatedProduct } from "./importer";
import { readGeneratedEntries, saveGeneratedEntry } from "./generatedCatalog";
import { loadModel } from "../interactions/models";

const dimensions = {
  width: { valueM: .52, source: "estimated" as const, evidence: "Image estimate" },
  height: { valueM: 1.8161, source: "product_text" as const, evidence: "Height 181.61 cm" },
  depth: { valueM: .2413, source: "estimated" as const, evidence: "Image estimate" },
};
const prepared: PreparedImport = { importId: "a".repeat(32), expiresAt: "2026-09-20T00:00:00Z", title: "Test lamp", category: "lamp", template: "custom", dimensions, warnings: ["Estimated size"], analysisMethod: "gpt", usage: { cached: false, inputTokens: 100, outputTokens: 100 } };
const asset = { id: "asset-test", productId: "generated-test", glbUrl: `/api/v1/models/assets/${"b".repeat(64)}.glb`, dimensionsM: [.52, 1.8161, .2413] as [number, number, number], status: "ready" as const, generationMethod: "gpt-blender" as const, pivot: "bottom-center" as const, forwardAxis: "+Z" as const, disclosure: "Generated by Sol in Blender. Estimated footprint." };
const queued: GenerationJob = { jobId: "c".repeat(32), status: "queued", dimensions, asset: null, error: null, cached: false };
const ready: GenerationJob = { ...queued, status: "ready", asset };
const product: Product = { id: asset.productId, title: "Test lamp", category: "lamp", priceUsd: 0, merchant: "Your image", sourceUrl: "", imageUrl: "", dimensionsM: asset.dimensionsM, styleTags: ["price-not-provided"], colorTags: [], modelAssetId: asset.id };
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status });

describe("real generation boundary", () => {
  it("preserves sourced identity, photos and price while using the confirmed model dimensions", () => {
    const source = { ...product, title: "Sourced lamp", priceUsd: 90, merchant: "Store", imageUrl: "https://example.com/lamp.jpg", dimensionsM: [1, 2, 1] as [number, number, number], styleTags: ["warm", "model-pending", "price-not-provided"] };
    const result = generatedProduct(prepared, asset, 85, "https://example.com/lamp", source);
    expect(result).toMatchObject({ id: source.id, title: source.title, priceUsd: 85, imageUrl: source.imageUrl, merchant: "Store", dimensionsM: asset.dimensionsM, styleTags: ["warm"], modelAssetId: asset.id });
    expect(generatedProduct(prepared, asset, null, "", source).styleTags).toContain("price-not-provided");
  });
  it("uses versioned endpoints and returns the real same-origin GLB URL", async () => {
    const fetcher = vi.fn().mockResolvedValueOnce(response(prepared)).mockResolvedValueOnce(response(queued, 202)).mockResolvedValueOnce(response(ready));
    const api = createGenerationClient(fetcher);
    expect(await api.prepare({ imageDataUrl: "data:image/png;base64,abc", mode: "live" })).toEqual(prepared);
    await api.generate(reviewedRequest(prepared, product.id, [.52, 1.8161, .2413]));
    expect((await api.job(queued.jobId)).asset?.glbUrl).toBe(asset.glbUrl);
    expect(fetcher.mock.calls.map(c => c[0])).toEqual(["/api/v1/models/prepare", "/api/v1/models/generate", `/api/v1/models/jobs/${queued.jobId}`]);
    expect(fetcher.mock.calls[0][1].body).toContain('"mode":"live"');
  });

  it("never retries a failed paid analysis and returns actionable backend errors", async () => {
    const fetcher = vi.fn().mockResolvedValue(response({ detail: "Session AI-call limit reached" }, 429));
    await expect(createGenerationClient(fetcher).prepare({ imageDataUrl: "x" })).rejects.toThrow("Session AI-call limit");
    expect(fetcher).toHaveBeenCalledTimes(1);
  });

  it("rejects malformed jobs and unsafe asset URLs", async () => {
    await expect(createGenerationClient(vi.fn().mockResolvedValue(response({ status: "ready" }))).job("x")).rejects.toThrow();
    await expect(createGenerationClient(vi.fn().mockResolvedValue(response({ ...ready, asset: { ...asset, glbUrl: "https://example.com/model.glb" } }))).job("x")).rejects.toThrow("unexpected model URL");
  });

  it("reports actual queued, generating and ready states", async () => {
    const api = { job: vi.fn().mockResolvedValueOnce({ ...queued, status: "generating" }).mockResolvedValueOnce(ready) };
    const states: string[] = [];
    expect(await waitForGeneration(queued, api, j => states.push(j.status), async () => {})).toEqual(ready);
    expect(states).toEqual(["queued", "generating", "ready"]);
  });

  it("stops on failed jobs and offers resume on long builds", async () => {
    const api = { job: vi.fn().mockResolvedValue(queued) };
    await expect(waitForGeneration({ ...queued, status: "failed", error: "Blender unavailable" }, api, () => {}, async () => {})).rejects.toThrow("Blender unavailable");
    expect(api.job).not.toHaveBeenCalled();
    await expect(waitForGeneration(queued, api, () => {}, async () => {})).rejects.toThrow("Resume");
    expect(api.job).toHaveBeenCalledTimes(160);
  });

  it("keeps untouched sizes exact, labels untouched guesses as accepted estimates, and never asks for a checkbox", () => {
    const inch = .0254;
    const req = reviewedRequest(prepared, "id", [Math.round(.52 / inch * 10) / 10 * inch, Math.round(1.8161 / inch * 10) / 10 * inch, Math.round(.2413 / inch * 10) / 10 * inch]);
    expect(req.dimensions).toEqual({ widthM: .52, heightM: 1.8161, depthM: .2413 });
    expect(req.estimatedAxes).toEqual(["width", "depth"]);
    expect(req.acceptEstimated).toBe(true);
    expect(req.confirmed).toBe(true);
    expect(dimensionDisclosure(dimensions)).toContain("Estimate — not measured");
  });

  it("treats a typed size as the user's measurement and rejects invalid sizes", () => {
    const req = reviewedRequest(prepared, "id", [.6, 1.8161, .2413]);
    expect(req.dimensions.widthM).toBe(.6);
    expect(req.estimatedAxes).toEqual(["depth"]);
    for (const n of [0, -3, 5.01, NaN, Infinity]) expect(() => reviewedRequest(prepared, "id", [n, 1.8161, .2413])).toThrow("between");
  });

  it("keeps explicitly estimated source text estimated even in an older cached response", () => {
    const p = { ...prepared, dimensions: { ...dimensions, width: { ...dimensions.width, source: "product_text" as const, evidence: "Width about 52 cm is an estimate" } } };
    expect(reviewedRequest(p, "id", [.52, 1.8161, .2413]).estimatedAxes).toContain("width");
  });

  it("rejects non-images and oversized files before paid analysis", async () => {
    await expect(furnitureImageDataUrl(new File(["x"], "test.txt", { type: "text/plain" }))).rejects.toThrow("image under 5 MB");
    await expect(furnitureImageDataUrl(new File([new Uint8Array(5_000_001)], "test.png", { type: "image/png" }))).rejects.toThrow("image under 5 MB");
  });

  it("persists generated metadata without uploaded images and restores it without duplicates", () => {
    let value = "[]";
    const storage = { getItem: () => value, setItem: (_k: string, v: string) => { value = v; } };
    saveGeneratedEntry({ product, asset }, storage);
    saveGeneratedEntry({ product, asset }, storage);
    expect(readGeneratedEntries(storage)).toEqual([{ product, asset }]);
    expect(value).not.toContain("data:image");
    value = JSON.stringify([{ product, asset: { ...asset, glbUrl: "javascript:bad" } }]);
    expect(readGeneratedEntries(storage)).toEqual([]);
  });

  it("does not turn failed generated GLB downloads into fake successful boxes", async () => {
    vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("unavailable", { status: 503 })));
    try {
      await expect(loadModel(product, asset)).rejects.toThrow("Could not load the generated GLB");
      await expect(loadModel(product, asset)).rejects.toThrow("Could not load the generated GLB");
      expect(fetch).toHaveBeenCalledTimes(2);
    } finally { vi.unstubAllGlobals(); }
  });
});
